### PR TITLE
Modernize build (2.440.3 baseline)

### PR DESCRIPTION
**Pull request by TobiX**
- Bill of material (see https://www.jenkins.io/doc/developer/tutorial-improve/use-plugin-bill-of-materials/)
- Jenkins ~~2.361.4~~ 2.440.3 baseline (about a year old, gets rid of all implied dependencies)
- Build against Java 11, test with 17 & 21

### Testing done

- Ran test suite locally with Java 17 & 21

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by TobiX** [comment]
Ping @GLundh & @jonsten - Needs to be triggered by a maintainer to accept the Jenkinsfile changes. Would be nice to get this (and maybe #17?) merged and released.

**Comment by GLundh** [comment]
Do I trigger it in the wrong way or something? Can't get a passing build.

**Comment by TobiX** [comment]
https://ci.jenkins.io/job/Plugins/job/downstream-build-cache-plugin/job/PR-16/2/console shows:
```
13:46:55  ‘Jenkinsfile’ has been modified in an untrusted revision
```
Hmm. I think you might need to push to the branch for Jenkins to "trust" the modification...

**Comment by GLundh** [comment]
I triggered a new build. Let's see if this work.

**Pull request merged**
